const project = [
  {
    id: 1,
    pro_img: "./assets/project_img/kNTsT1.png",
    pro_name: "kNTsT Ecommerce",
    pro_desc:
      "Ecommerce Football clothes website that allow user to buy the products.",
    proGit_Url: "https://github.com/Kheng-Uzamaki/kNTsT-Project",
    pro_liveDemo: "https://test-project-nu-six.vercel.app/",
  },
  {
    id: 2,
    pro_img: "./assets/project_img/social-clone.png",
    pro_name: "Linkedin Clone",
    pro_desc: "Clone Linkedin wep-page by using HTML,CSS and JavaScript.",
    proGit_Url: "https://github.com/Kheng-Uzamaki/linkedin-clone",
    pro_liveDemo: "https://linkedin-clone-alpha-gray.vercel.app/",
  },
  {
    id: 3,
    pro_img: "./assets/project_img/socialBook.png",
    pro_name: "SocialBook",
    pro_desc: "Clone Facebook wep-page by using HTML,CSS and JavaScript.",
    proGit_Url: "https://github.com/Kheng-Uzamaki/Social-clone",
    pro_liveDemo: "https://social-clone-sage.vercel.app/",
  },
  {
    id: 4,
    pro_img: "./assets/project_img/v-tube.png",
    pro_name: "V-Tube",
    pro_desc: "Clone Youtube wep-page by using HTML,CSS and JavaScript.",
    proGit_Url: "https://github.com/Kheng-Uzamaki/V-tube",
    pro_liveDemo: "https://v-tube-alpha.vercel.app/",
  },
  {
    id: 5,
    pro_img: "./assets/project_img/netflex.png",
    pro_name: "Netflix Landpage",
    pro_desc: "Clone Netflix wep-page by using HTML,CSS and JavaScript.",
    proGit_Url: "https://github.com/Kheng-Uzamaki/netflix-landpage",
    pro_liveDemo: "https://netflix-landpage.vercel.app/",
  },
  {
    id: 6,
    pro_img: "./assets/project_img/QR.png",
    pro_name: "QR Generator",
    pro_desc: "QR Generator wep-page by using HTML,CSS and JavaScript.",
    proGit_Url: "https://github.com/Kheng-Uzamaki/QR-Generator",
    pro_liveDemo: "https://qr-generator-two-mu.vercel.app/",
  },
  {
    id: 7,
    pro_img: "./assets/project_img/Quiz.png",
    pro_name: "Quiz App",
    pro_desc: "Quiz App wep-page by using HTML,CSS and JavaScript.",
    proGit_Url: "https://github.com/Kheng-Uzamaki/QiuzApp",
    pro_liveDemo: "https://qiuz-app-one.vercel.app/",
  },
  {
    id: 8,
    pro_img: "./assets/project_img/Note.png",
    pro_name: "Note App",
    pro_desc: "Note App wep-page by using HTML,CSS and JavaScript.",
    proGit_Url: "https://github.com/Kheng-Uzamaki/NoteApp",
    pro_liveDemo: "https://note-app-rose-nine.vercel.app/",
  },
  {
    id: 9,
    pro_img: "./assets/project_img/to-do.png",
    pro_name: "To-Do-List App",
    pro_desc: "To-Do-List App wep-page by using HTML,CSS and JavaScript.",
    proGit_Url: "https://github.com/Kheng-Uzamaki/Kheng-ToDo-List",
    pro_liveDemo: "https://kheng-to-do-list.vercel.app/",
  },
  {
    id: 10,
    pro_img: "./assets/project_img/calculator.png",
    pro_name: "Calculator App",
    pro_desc: "Calculator App wep-page by using HTML,CSS and JavaScript.",
    proGit_Url: "https://github.com/Kheng-Uzamaki/Caculator",
    pro_liveDemo: "https://calculator-app-zeta-steel.vercel.app/",
  },
  {
    id: 11,
    pro_img: "./assets/project_img/Weather.png",
    pro_name: "Weather API App",
    pro_desc: "Weather API App wep-page by using HTML,CSS and JavaScript.",
    proGit_Url: "https://github.com/Kheng-Uzamaki/Kheng-Weather",
    pro_liveDemo: "https://kheng-weather.vercel.app/",
  },
  {
    id: 12,
    pro_img: "./assets/project_img/age-cal.png",
    pro_name: "Age Calculator App",
    pro_desc: "Age Calculator App wep-page by using HTML,CSS and JavaScript.",
    proGit_Url: "https://github.com/Kheng-Uzamaki/AgeCalculator",
    pro_liveDemo: "https://age-calculator-five-theta.vercel.app/",
  },
];
export default project;
